# Generated by Django 4.1.5 on 2023-01-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_stock_cooker_stockhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='suppliedproduct',
            name='supplies',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='products',
        ),
        migrations.RemoveField(
            model_name='supplies',
            name='products',
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.cookerrank'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.measure'),
        ),
        migrations.CreateModel(
            name='StockProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('expired_at', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product')),
            ],
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.stockproduct'),
        ),
        migrations.AlterField(
            model_name='suppliedproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.supplierproduct'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
