# Generated by Django 4.1.5 on 2023-01-30 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_supplierproduct_product_supplierproduct_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliedproduct',
            name='suplie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.supplies'),
        ),
    ]
