# Generated by Django 4.1.5 on 2023-01-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_suppliedproduct_suplie'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies',
            name='realised',
            field=models.BooleanField(default=False),
        ),
    ]
